### ISSUE TITLE
Civic KYC Contract (Different package initialization)

### ISSUE THREAD

**Issue by deuszex** [CasperLabs/civic-contract#4]
Rewrite contract package initialisation using
```
storage::new_contract(entry_points, named_keys, hash_name, uref_name);
```

**Comment by astro019** [comment]
**contract_package_hash** is required for the event emit, so contract package initialisation using `storage:new_contract()` is disassembled to store the **contract_package_hash** inside the current context

**Comment by deuszex** [comment]
You can fetch the package_hash via the call_stacks last entry in any point in a stored_contract context.

**Comment by astro019** [comment]
> You can fetch the package_hash via the call_stacks last entry in any point in a stored_contract context.

yeah

**Comment by deuszex** [comment]
Correct it does not, but you can still use `runtime::get_named_key` because the package hash was stored into the account context, and so you can fetch it
